# ===================================================================
# Pixi Profile-Based Configuration
# ===================================================================
# This file defines different tool profiles for various use cases
# Profiles allow selective installation of tool sets based on needs
#
# Usage:
# - pixi install --environment default  # Install base tools only  
# - pixi install --environment dev      # Install development tools
# - pixi shell --environment dev        # Activate development environment
#
# Documentation: https://pixi.sh/

[project]
name = "chezmoi"
version = "0.1.0"
description = "ChezMoi dotfiles management with Pixi for development tools"
authors = ["Dale Hancock <dale@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

# ===================================================================
# Default Dependencies - Essential Tools
# ===================================================================
[dependencies]
# Navigation & Search Tools
fzf = "*"                # Fuzzy finder for files, commands, and more
ripgrep = "*"            # Ultra-fast text search (replaces grep)
fd-find = "*"            # User-friendly find alternative
tldr = "*"               # Simplified man pages with examples
zoxide = "*"             # Smart cd command that learns your habits

# Prompt & Shell Enhancements
starship = "*"           # Cross-shell prompt (configured in starship.toml)
direnv = "*"             # Per-directory environment variables
mcfly = "*"              # Intelligent history search with fuzzy matching

# System Utilities
eza = "*"                # Modern ls replacement with git integration
duf = "*"                # Disk usage/free utility with better output
btop = "*"               # Beautiful system monitor (replaces top/htop)
ncdu = "*"               # NCurses disk usage analyzer
tmux = "*"               # Terminal multiplexer for session management
dust = "*"               # More intuitive version of du

# Essential Tools
chezmoi = "*"            # Dotfile manager
jq = "*"                 # JSON processor and query tool
sd = "*"                 # Intuitive find & replace CLI (sed alternative)
tealdeer = "*"           # Fast tldr client for quick help

# Editors
neovim = "*"             # Modern Vim with better defaults and Lua config

# Linux-specific tools
bat = "*"                # Cat with syntax highlighting and git integration
atuin = "*"              # Enhanced shell history with search and sync
tig = "*"                # Text-mode interface for git

# ===================================================================
# Development Dependencies - Additional Dev Tools  
# ===================================================================
[feature.dev.dependencies]
# Developer & Data Tools
git-delta = "*"          # Syntax-highlighted git diffs
gh = "*"                 # GitHub CLI for repository management
just = "*"               # Command runner and task automation
gitui = "*"              # Terminal UI for git operations

# Network & System Tools
httpie = "*"             # User-friendly HTTP client
curlie = "*"             # curl with httpie-like interface
fx = "*"                 # Interactive JSON viewer and processor

# Performance & Benchmarking
hyperfine = "*"          # Command-line benchmarking tool
entr = "*"               # Run commands when files change
htop = "*"               # Interactive process viewer (fallback to btop)

# ===================================================================
# Environment Definitions
# ===================================================================
[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

# ===================================================================
# Installation Notes
# ===================================================================
# Tools not available in conda-forge are installed via run_once_setup_tools.sh.tmpl
# using apt, cargo, or other package managers. These include:
# - bandwhich: Terminal bandwidth utilization tool (install via cargo)
# - qsv/xsv: CSV processing tools (install via cargo)
# - gum: Interactive shell utilities (install via go/cargo)
# - lazydocker: Terminal UI for docker (install via go)
# 
# As these tools become available in conda-forge, move them to the appropriate dependencies

